name: "Docker Build"
description: "Build, push, and optionally sign container images with standardized tagging"

inputs:
  image:
    description: "Full image name (e.g., ghcr.io/org/app)"
    required: true
  app-name:
    description: "Application name for OCI labels"
    required: true
  app-description:
    description: "Application description for OCI labels"
    required: false
    default: ""
  registry:
    description: "Container registry hostname"
    required: false
    default: "ghcr.io"
  registry-username:
    description: "Registry username"
    required: true
  registry-password:
    description: "Registry password or token"
    required: true
  sign:
    description: "Sign image with Cosign (keyless)"
    required: false
    default: "false"
  context:
    description: "Docker build context"
    required: false
    default: "."
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: "Dockerfile"

outputs:
  digest:
    description: "Image digest"
    value: ${{ steps.build.outputs.digest }}
  tags:
    description: "Generated image tags"
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          type=sha,prefix=${{ github.event_name == 'pull_request' && format('pr-{0}-sha-', github.event.pull_request.number) || 'sha-' }},format=long
          type=raw,value=pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' }}
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        labels: |
          org.opencontainers.image.title=${{ inputs.app-name }}
          org.opencontainers.image.description=${{ inputs.app-description }}

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Install Cosign
      if: inputs.sign == 'true'
      uses: sigstore/cosign-installer@v3

    - name: Sign container image
      if: inputs.sign == 'true'
      shell: bash
      run: |
        cosign sign --yes \
          ${{ inputs.image }}@${{ steps.build.outputs.digest }}
